/**
 * services/authErrorCodes.js
 *
 * Canonical machine-readable error codes for the authentication lifecycle.
 *
 * Web and mobile clients should branch on these codes (NOT on HTTP status
 * alone, NOT on free-text error messages). Codes are stable and additive:
 * existing values must not change semantics; new flows append new codes.
 */

const AUTH_ERROR_CODES = Object.freeze({
  // Generic
  VALIDATION_ERROR: 'AUTH_VALIDATION_ERROR',
  INTERNAL_ERROR: 'AUTH_INTERNAL_ERROR',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  NOT_FOUND: 'AUTH_NOT_FOUND',

  // Login
  MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',

  // MFA
  MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  MFA_INVALID: 'AUTH_MFA_INVALID',
  MFA_DISABLED: 'AUTH_MFA_DISABLED',
  MFA_RESEND_FAILED: 'AUTH_MFA_RESEND_FAILED',
  MFA_CHALLENGE_PENDING: 'AUTH_MFA_CHALLENGE_PENDING',

  // Token lifecycle
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',

  // Password change (authenticated user)
  CURRENT_PASSWORD_REQUIRED: 'AUTH_CURRENT_PASSWORD_REQUIRED',
  CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  NEW_PASSWORD_REQUIRED: 'AUTH_NEW_PASSWORD_REQUIRED',
  CONFIRM_PASSWORD_REQUIRED: 'AUTH_CONFIRM_PASSWORD_REQUIRED',
  PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  PASSWORD_REUSE: 'AUTH_PASSWORD_REUSE',
  WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  UNAUTHORIZED_USER_CONTEXT: 'AUTH_UNAUTHORIZED_USER_CONTEXT',

  // Forgot/reset password (unauthenticated recovery)
  RESET_REQUEST_FAILED: 'AUTH_RESET_REQUEST_FAILED',
  RESET_CODE_INVALID: 'AUTH_RESET_CODE_INVALID',
  RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  RESET_FAILED: 'AUTH_RESET_FAILED',

  // Registration / OAuth
  REGISTER_FAILED: 'AUTH_REGISTER_FAILED',
  OAUTH_EXCHANGE_FAILED: 'AUTH_OAUTH_EXCHANGE_FAILED',

  // Profile / session
  PROFILE_LOAD_FAILED: 'AUTH_PROFILE_LOAD_FAILED',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  TRUSTED_DEVICE_REVOKE_FAILED: 'AUTH_TRUSTED_DEVICE_REVOKE_FAILED',
});

/**
 * Default HTTP status for a given canonical auth code. Controllers can still
 * override per-call when they have more context.
 */
const STATUS_BY_CODE = Object.freeze({
  [AUTH_ERROR_CODES.VALIDATION_ERROR]: 400,
  [AUTH_ERROR_CODES.INTERNAL_ERROR]: 500,
  [AUTH_ERROR_CODES.RATE_LIMITED]: 429,
  [AUTH_ERROR_CODES.NOT_FOUND]: 404,

  [AUTH_ERROR_CODES.MISSING_FIELDS]: 400,
  [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [AUTH_ERROR_CODES.ACCOUNT_LOCKED]: 423,
  [AUTH_ERROR_CODES.ACCOUNT_DISABLED]: 403,

  [AUTH_ERROR_CODES.MFA_REQUIRED]: 401,
  [AUTH_ERROR_CODES.MFA_INVALID]: 401,
  [AUTH_ERROR_CODES.MFA_DISABLED]: 404,
  [AUTH_ERROR_CODES.MFA_RESEND_FAILED]: 500,
  [AUTH_ERROR_CODES.MFA_CHALLENGE_PENDING]: 202,

  [AUTH_ERROR_CODES.TOKEN_INVALID]: 401,
  [AUTH_ERROR_CODES.TOKEN_EXPIRED]: 401,
  [AUTH_ERROR_CODES.REFRESH_FAILED]: 401,
  [AUTH_ERROR_CODES.LOGOUT_FAILED]: 500,

  [AUTH_ERROR_CODES.CURRENT_PASSWORD_REQUIRED]: 400,
  [AUTH_ERROR_CODES.CURRENT_PASSWORD_INVALID]: 401,
  [AUTH_ERROR_CODES.NEW_PASSWORD_REQUIRED]: 400,
  [AUTH_ERROR_CODES.CONFIRM_PASSWORD_REQUIRED]: 400,
  [AUTH_ERROR_CODES.PASSWORD_MISMATCH]: 400,
  [AUTH_ERROR_CODES.PASSWORD_REUSE]: 400,
  [AUTH_ERROR_CODES.WEAK_PASSWORD]: 400,
  [AUTH_ERROR_CODES.UNAUTHORIZED_USER_CONTEXT]: 403,

  [AUTH_ERROR_CODES.RESET_REQUEST_FAILED]: 500,
  [AUTH_ERROR_CODES.RESET_CODE_INVALID]: 401,
  [AUTH_ERROR_CODES.RESET_TOKEN_INVALID]: 401,
  [AUTH_ERROR_CODES.RESET_FAILED]: 500,

  [AUTH_ERROR_CODES.REGISTER_FAILED]: 400,
  [AUTH_ERROR_CODES.OAUTH_EXCHANGE_FAILED]: 401,

  [AUTH_ERROR_CODES.PROFILE_LOAD_FAILED]: 500,
  [AUTH_ERROR_CODES.USER_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.TRUSTED_DEVICE_REVOKE_FAILED]: 500,
});

function statusForAuthCode(code) {
  return STATUS_BY_CODE[code];
}

module.exports = {
  AUTH_ERROR_CODES,
  statusForAuthCode,
};
