-- Recipe reviews for both admin-managed catalog recipes and approved community recipes.
-- source_type keeps recipes and recipe_library roles separate.

create table if not exists public.recipe_reviews (
  id bigint generated by default as identity primary key,
  source_type text not null
    check (source_type in ('recipe_library', 'community')),
  recipe_id bigint not null,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 2 and 1200),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_type, recipe_id, user_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists recipe_reviews_set_updated_at on public.recipe_reviews;
create trigger recipe_reviews_set_updated_at
before update on public.recipe_reviews
for each row
execute function public.set_updated_at();

create index if not exists recipe_reviews_lookup_idx
  on public.recipe_reviews (source_type, recipe_id, is_hidden, created_at desc);

create index if not exists recipe_reviews_user_idx
  on public.recipe_reviews (user_id, created_at desc);

alter table public.recipe_reviews enable row level security;

drop policy if exists "Visible recipe reviews are readable" on public.recipe_reviews;
create policy "Visible recipe reviews are readable"
on public.recipe_reviews
for select
using (is_hidden = false);

drop policy if exists "Users can insert own recipe reviews" on public.recipe_reviews;
create policy "Users can insert own recipe reviews"
on public.recipe_reviews
for insert
with check (auth.uid() is not null);

drop policy if exists "Users can update own recipe reviews" on public.recipe_reviews;
create policy "Users can update own recipe reviews"
on public.recipe_reviews
for update
using (auth.uid() is not null);

comment on table public.recipe_reviews is
  'User star ratings and comments for public recipe_library rows and approved community recipes.';
