-- Recipe Library
-- Purpose:
-- - One central recipe table for admin catalog recipes, private user recipes, and community shared recipes.
-- - Replaces long-term dependence on legacy weeklyrecipes for public meals.
-- - Supports dish-name-only import followed by AI enrichment and admin review.
--
-- Run this in Supabase SQL Editor after review.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.recipe_library (
  id bigint generated by default as identity primary key,

  -- Ownership / identity
  owner_user_id bigint references public.users(user_id) on update cascade on delete set null,
  legacy_recipe_id bigint,
  slug text unique,
  recipe_name text not null,
  dish_name text not null,
  display_name text,
  description text,

  -- Visibility model
  visibility text not null default 'private'
    check (visibility in ('private', 'public', 'community', 'community_pending', 'unlisted')),
  source text not null default 'user_created'
    check (source in ('user_created', 'admin_created', 'admin_ai', 'imported', 'legacy_migration')),
  is_published boolean not null default false,
  data_status text not null default 'draft'
    check (data_status in ('draft', 'queued', 'ai_enriched', 'needs_review', 'user_private', 'reviewed', 'published', 'rejected')),

  -- Moderation for community sharing
  moderation_status text not null default 'not_required'
    check (moderation_status in ('not_required', 'pending', 'approved', 'rejected')),
  moderation_reason text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by bigint references public.users(user_id) on update cascade on delete set null,
  published_at timestamptz,
  trashed_at timestamptz,
  trashed_by bigint references public.users(user_id) on update cascade on delete set null,
  trash_reason text,
  trash_snapshot jsonb check (trash_snapshot is null or jsonb_typeof(trash_snapshot) = 'object'),

  -- Classification
  meal_type text not null default 'breakfast'
    check (meal_type in ('breakfast', 'lunch', 'dinner', 'other')),
  cuisine_id integer references public.cuisines(id) on update cascade on delete set null,
  cuisine_name_snapshot text,
  cooking_method_id integer references public.cooking_methods(id) on update cascade on delete set null,
  cooking_method_name_snapshot text,
  difficulty text check (difficulty is null or difficulty in ('easy', 'medium', 'hard')),
  spice_level text check (spice_level is null or spice_level in ('none', 'mild', 'medium', 'hot')),

  -- Time / serving
  prep_time_minutes integer check (prep_time_minutes is null or prep_time_minutes >= 0),
  cook_time_minutes integer check (cook_time_minutes is null or cook_time_minutes >= 0),
  total_time_minutes integer generated always as (
    coalesce(prep_time_minutes, 0) + coalesce(cook_time_minutes, 0)
  ) stored,
  servings numeric(6, 2) check (servings is null or servings > 0),
  serving_size text,

  -- Recipe body
  ingredients jsonb not null default '[]'::jsonb
    check (jsonb_typeof(ingredients) = 'array'),
  instructions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(instructions) = 'array'),
  equipment text[] not null default '{}',
  tips text[] not null default '{}',
  storage_instructions text,
  reheating_instructions text,
  notes text,

  -- Suitability / tags
  dietary_tags text[] not null default '{}',
  health_tags text[] not null default '{}',
  allergens text[] not null default '{}',
  avoid_for_conditions text[] not null default '{}',
  suitable_goals text[] not null default '{}',

  -- Nutrition per serving
  calories numeric(10, 2) check (calories is null or calories >= 0),
  protein numeric(10, 2) check (protein is null or protein >= 0),
  fat numeric(10, 2) check (fat is null or fat >= 0),
  saturated_fat numeric(10, 2) check (saturated_fat is null or saturated_fat >= 0),
  carbohydrates numeric(10, 2) check (carbohydrates is null or carbohydrates >= 0),
  fiber numeric(10, 2) check (fiber is null or fiber >= 0),
  sugar numeric(10, 2) check (sugar is null or sugar >= 0),
  sodium numeric(10, 2) check (sodium is null or sodium >= 0),
  potassium numeric(10, 2) check (potassium is null or potassium >= 0),
  calcium numeric(10, 2) check (calcium is null or calcium >= 0),
  iron numeric(10, 2) check (iron is null or iron >= 0),
  vitamin_a numeric(10, 2) check (vitamin_a is null or vitamin_a >= 0),
  vitamin_c numeric(10, 2) check (vitamin_c is null or vitamin_c >= 0),

  -- Remote image metadata. image_url is the URL rendered by the frontend.
  image_url text,
  image_original_url text,
  image_source text,
  image_source_url text,
  image_attribution text,
  image_license text,
  image_confidence numeric(4, 3) check (image_confidence is null or image_confidence between 0 and 1),
  image_fetched_at timestamptz,

  -- Social counters. Keep counters denormalized for fast Explore Community cards.
  view_count integer not null default 0 check (view_count >= 0),
  like_count integer not null default 0 check (like_count >= 0),
  save_count integer not null default 0 check (save_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  report_count integer not null default 0 check (report_count >= 0),

  -- AI enrichment / audit
  ai_generated boolean not null default false,
  ai_provider text,
  ai_model text,
  ai_prompt_version text,
  ai_confidence numeric(4, 3) check (ai_confidence is null or ai_confidence between 0 and 1),
  ai_raw_response jsonb,
  quality_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint recipe_library_publish_visibility_check check (
    (is_published = false)
    or (visibility in ('public', 'community', 'unlisted') and data_status in ('reviewed', 'published'))
  )
);

drop trigger if exists recipe_library_set_updated_at on public.recipe_library;
create trigger recipe_library_set_updated_at
before update on public.recipe_library
for each row
execute function public.set_updated_at();

create index if not exists recipe_library_owner_idx
  on public.recipe_library (owner_user_id, created_at desc);

create index if not exists recipe_library_visibility_idx
  on public.recipe_library (visibility, is_published, meal_type, cuisine_id, cooking_method_id);

create index if not exists recipe_library_moderation_idx
  on public.recipe_library (moderation_status, submitted_at);

create index if not exists recipe_library_trash_idx
  on public.recipe_library (trashed_at desc);

create index if not exists recipe_library_name_idx
  on public.recipe_library (lower(recipe_name));

create index if not exists recipe_library_dish_name_idx
  on public.recipe_library (lower(dish_name));

create index if not exists recipe_library_dietary_tags_idx
  on public.recipe_library using gin (dietary_tags);

create index if not exists recipe_library_health_tags_idx
  on public.recipe_library using gin (health_tags);

create index if not exists recipe_library_allergens_idx
  on public.recipe_library using gin (allergens);

create index if not exists recipe_library_ingredients_idx
  on public.recipe_library using gin (ingredients);

create table if not exists public.recipe_library_import_queue (
  id uuid primary key default gen_random_uuid(),
  dish_name text not null,
  meal_type text check (meal_type is null or meal_type in ('breakfast', 'lunch', 'dinner', 'other')),
  cuisine_hint text,
  cooking_method_hint text,
  admin_notes text,
  status text not null default 'pending'
    check (status in ('pending', 'enriching', 'enriched', 'failed', 'imported', 'rejected')),
  target_recipe_id bigint references public.recipe_library(id) on delete set null,
  error_message text,
  ai_raw_response jsonb,
  created_by bigint references public.users(user_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists recipe_library_import_queue_set_updated_at on public.recipe_library_import_queue;
create trigger recipe_library_import_queue_set_updated_at
before update on public.recipe_library_import_queue
for each row
execute function public.set_updated_at();

create index if not exists recipe_library_import_queue_status_idx
  on public.recipe_library_import_queue (status, created_at);

create index if not exists recipe_library_import_queue_name_idx
  on public.recipe_library_import_queue (lower(dish_name));

create table if not exists public.recipe_library_likes (
  recipe_id bigint not null references public.recipe_library(id) on delete cascade,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recipe_id, user_id)
);

create table if not exists public.recipe_library_saves (
  recipe_id bigint not null references public.recipe_library(id) on delete cascade,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recipe_id, user_id)
);

create table if not exists public.recipe_library_comments (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipe_library(id) on delete cascade,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  body text not null,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists recipe_library_comments_set_updated_at on public.recipe_library_comments;
create trigger recipe_library_comments_set_updated_at
before update on public.recipe_library_comments
for each row
execute function public.set_updated_at();

create table if not exists public.recipe_library_reports (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipe_library(id) on delete cascade,
  user_id bigint references public.users(user_id) on update cascade on delete set null,
  reason text not null,
  details text,
  status text not null default 'open'
    check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists recipe_library_reports_set_updated_at on public.recipe_library_reports;
create trigger recipe_library_reports_set_updated_at
before update on public.recipe_library_reports
for each row
execute function public.set_updated_at();

create or replace view public.published_recipe_library as
select *
from public.recipe_library
where is_published = true
  and visibility in ('public', 'community', 'unlisted')
  and data_status in ('reviewed', 'published')
  and trashed_at is null;

create or replace view public.community_recipe_explore as
select *
from public.recipe_library
where is_published = true
  and visibility = 'community'
  and moderation_status = 'approved'
  and data_status in ('reviewed', 'published')
  and trashed_at is null;

alter table public.recipe_library enable row level security;
alter table public.recipe_library_import_queue enable row level security;
alter table public.recipe_library_likes enable row level security;
alter table public.recipe_library_saves enable row level security;
alter table public.recipe_library_comments enable row level security;
alter table public.recipe_library_reports enable row level security;

drop policy if exists "Recipe library published rows are readable" on public.recipe_library;
create policy "Recipe library published rows are readable"
on public.recipe_library
for select
using (
  is_published = true
  and visibility in ('public', 'community', 'unlisted')
  and data_status in ('reviewed', 'published')
  and trashed_at is null
);

drop policy if exists "Visible comments are readable for published recipes" on public.recipe_library_comments;
create policy "Visible comments are readable for published recipes"
on public.recipe_library_comments
for select
using (
  is_hidden = false
  and exists (
    select 1
    from public.recipe_library r
    where r.id = recipe_id
      and r.is_published = true
      and r.visibility in ('public', 'community')
      and r.trashed_at is null
  )
);

comment on table public.recipe_library is
  'Central recipe table for public catalog, private user recipes, and community shared recipes.';

comment on table public.recipe_library_import_queue is
  'Admin input queue for dish names before AI enrichment into recipe_library.';
